### ISSUE TITLE
suppress messages matching certain patterns 

### ISSUE THREAD

**Issue by dch** [termoose/irccloud#8]
cool project :rocket: 

it would be nice to be able to suppress messages that match a certain pattern. A specific example is joins. quits, & timeouts

**Comment by termoose** [comment]
Thanks 💥! I've wanted this as well, some channels are really huge with loads of leave/join messages cluttering up my chat buffers. I might make a quick feature to just turn on/off such messages with a config parameter. But long term I'd like all chat events to be some struct that implement `Stringer`, I can then easily collapse multiple join/leaves into one single line for example. Now they are just stupid strings dumped in a buffer. Could maybe even expand/collapse such groups with a key combo

**Comment by termoose** [comment]
Added a simple implementation of this, can be enabled by setting `only_messages: true` in your config file.
