### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by TehPeGaSuS** [termoose/irccloud#9]
@termoose 

I tried to use **termoose** with my subscriber account.

My `/home/icka/.config/irccloud/config.yaml`:
```
username:my_email@gmail.com
password: my_password
triggers:
  - cakes
last_chan: ""
only_messages: false
```

When starting **termoose** with `/home/icka/go/bin/irccloud`, I'm presented with a black screen.

When i try to scroll in the channel buffer, with `PgUp/PgDown`, **termoose** closes itself with the following error(s):
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x75ae3b]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000344620)
	/home/pegasus/go/src/github.com/rivo/tview/application.go:243 +0x82
panic(0x7b6380, 0xb08f80)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/termoose/irccloud/ui.(*channel).Scroll(...)
	/home/icka/go/src/github.com/termoose/irccloud/ui/channels.go:44
github.com/termoose/irccloud/ui.(*View).Start.func2(0xc00000eee0, 0xc00009fb70)
	/home/icka/go/src/github.com/termoose/irccloud/ui/ui.go:86 +0xcb
github.com/rivo/tview.(*Application).Run(0xc000344620, 0x0, 0x0)
	/home/icka/go/src/github.com/rivo/tview/application.go:318 +0x898
github.com/termoose/irccloud/ui.(*View).Start(0xc000106af0)
	/home/icka/go/src/github.com/termoose/irccloud/ui/ui.go:109 +0x382
main.main()
	/home/icka/go/src/github.com/termoose/irccloud/main.go:64 +0x3a2
```

Cheers

**Comment by termoose** [comment]
Sorry not able to reproduce, was this config generated by `irccloud` on the first run? There should at least be a space after `username:`, but that might be a copy/paste error? If that was the case it would say `panic: Invalid config format!` anyway

**Comment by TehPeGaSuS** [comment]
> Sorry not able to reproduce, was this config generated by `irccloud` on the first run? There should at least be a space after `username:`, but that might be a copy/paste error? If that was the case it would say `panic: Invalid config format!` anyway

I've copied the example from GitHub, I believe.

So, I've deleted the edited config and ran `/home/icka/go/bin/irccloud` to create a new dummy config.

Fun fact: `/home/icka/go/bin/irccloud` works, but `cd /home/icka/go/bin && ./irccloud` does not (just found it out now)

**Comment by TehPeGaSuS** [comment]
This seems to have been a **PEBCAK**.

Closing as it seems to have been a config issue (probably related to YAML syntax or something).
